### ISSUE TITLE
ERROR: FLOTIQ: You must specify API token

### ISSUE THREAD

**Issue by valentina-paniza** [flotiq/gatsby-starter-products#20] opened 2021-10-22 18:37 UTC
Hi! I have created a .env file inside the project directory and added the read and write flotiq api key as:
GATSBY_FLOTIQ_API_KEY=MY_READ_AND_WRITE_API_KEY

I have tried adding it as well on the .flotiq directory, but the error persists

**Comment by CiotkaCierpienia** [comment] 2022-02-22 12:42
Hi,
Sorry for the delay, but unfortunately, I cannot reproduce your problem. Did you change `MY_READ_AND_WRITE_API_KEY` to your real API key from the Flotiq account? Eventually, can you delete node_modules and install everything once more? The version of gatsby-cli, flotiq-cli and node will also help reproduce your issue.

**Comment by CiotkaCierpienia** [comment] 2022-03-09 12:24
Hello, as there is no answer, I'm closing this issue. We have new and better starters for products (this starter will be locked as read-only shortly):
- https://github.com/flotiq/flotiq-gatsby-shop-1
- https://github.com/flotiq/flotiq-gatsby-shop-2

**Closed as completed by CiotkaCierpienia** 2022-03-09 12:24 UTC
